# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "NodaTime"; version = "3.1.6"; sha256 = "00bnhm37f2wfzz1nm4lqasx5bjw6q37imr19m31hnj2sdvrhlbma"; })
  (fetchNuGet { pname = "NodaTime.Testing"; version = "3.1.6"; sha256 = "18b2b3jd0sgay1jgrqdwwh6gvrfmpnd5wjj06m0wfywy478lpz66"; })
  (fetchNuGet { pname = "System.Runtime.CompilerServices.Unsafe"; version = "4.7.1"; sha256 = "119br3pd85lq8zcgh4f60jzmv1g976q1kdgi3hvqdlhfbw6siz2j"; })
]
